name: test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1

      - uses: Swatinem/rust-cache@v1

      - name: Run cargo fmt
        run: cargo fmt -- --check

      - name: Run cargo clippy
        run: cargo clippy

      - name: Download test images
        run: curl https://qoiformat.org/qoi_test_images.zip -o qoi_test_images.zip

      - name: Unzip test images
        run: unzip qoi_test_images

      - name: Run cargo test
        run: cargo test --release