name: test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1

      - uses: Swatinem/rust-cache@v1

      - name: Run cargo fmt
        run: cargo fmt -- --check

      - name: Run cargo test
        run: cargo test --release